shadow = true;
shadow-radius = 14;
shadow-offset-x = -7;
shadow-offset-y = -7;
shadow-opacity = 0.5;

fading = true;
fade-in-step = 0.028;
fade-out-step = 0.028;

corner-radius = 10;

backend = "glx";
vsync = true;

opacity-rule = [
  "88:class_g = 'kitty'"
];
