shadow = true;
shadow-radius = 10;
shadow-offset-x = -5;
shadow-offset-y = -5;
shadow-opacity = 0.5;

fading = true;
fade-in-step = 0.035;
fade-out-step = 0.035;

corner-radius = 6;

backend = "glx";
vsync = true;

opacity-rule = [
  "92:class_g = 'kitty'"
];
