#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           10
bspc config top_padding          34
bspc config bottom_padding       0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config focus_follows_pointer true

bspc config normal_border_color   "#4A3723"
bspc config active_border_color   "#694C2C"
bspc config focused_border_color  "#CB8E37"

# autostart
killall -q polybar; polybar main &
picom --daemon &
feh --bg-fill ~/.local/share/rixi/wallpaper/wall.png &
