#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           12
bspc config top_padding          36
bspc config bottom_padding       0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config focus_follows_pointer true

bspc config normal_border_color   "#402E55"
bspc config active_border_color   "#96689F"
bspc config focused_border_color  "#EAAF62"

# autostart
killall -q polybar; polybar main &
picom --daemon &
feh --bg-fill ~/.local/share/rixi/wallpaper/wall.png &
